name: Deploy Python 3.12
on: [push]
jobs:
  build:
    runs-on: windows
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependecies
      run: |
        make install
    - name: Lint
      run: |
        make Lint
    - name: Test
      run: |
        make Test