name: CI/CD Pipeline

on:
  push:
    branches: "main" 

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      #Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      #Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      #Installa dipendenze
      - name: Install dependencies
        run: make install

      #Linting
      - name: Run linting
        run: make lint

      #Unit test
      - name: Run tests
        run: make test

      #Build package Python
      - name: Build package
        run: make build

      #Build Docker image
      - name: Build Docker image
        run: docker build -t cifar_trainer .
      
      #run the docker container to train
      - name: Run training container
        run: docker run --name cifar_trainer_container cifar_trainer
      
      #extract model.pt file from the container
      - name: copy model.pt from container
        run: docker cp cifar_trainer_container:/app/results/model.pt model.pt

      #upload final tensor.pt as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pt
      
      #clean up container
      - name: Remove container
        run: docker rm cifar_trainer_container